spring:
  kafka:
    producer:
      acks: -1
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        linger.ms: 1
        spring.json.trusted.packages: org.nowak.dto.ClientRequest
    topic-json:
      name: my-topic
  rest-client:
    url: http://localhost:8081/api/user
